cmd:
  type: python-venv
  command:
    default: python -u run.py
  path:
    default: ~/.opereto/operetovenv
item_properties:
-   editor: text
    key: worker_pod_id
    direction: input
    mandatory: true
    type: text
    value:
    help: Custom worker pod identifier
-   editor: text
    key: worker_pod_path
    direction: input
    mandatory: true
    type: text
    value:
    help: The path to file or directory on the custom worker pod
-   editor: text
    key: current_path
    direction: input
    mandatory: false
    type: text
    value:
    help: The local path to file or directory on the opereto worker pod. If not provided, service work directory is used.
-   editor: selectbox
    key: copy_direction
    direction: input
    mandatory: true
    type: text
    store:
        copy_to: copy_to
        copy_from: copy_from
    value: copy_from
    help: Identifying the source and destination for the copy operations
-   editor: number
    key: aggregation_interval
    direction: input
    mandatory: false
    type: integer
    value: 0
    help: If more then 0, copy will run in a loop periodically based on the interval time provided
timeout: 600
type: action